# Generated by Django 3.0.6 on 2020-08-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='work_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Vendor'),
        ),
    ]
