# Generated by Django 3.0.8 on 2020-08-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200804_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Cook'), (3, 'VendorOwner'), (4, 'Manager')]),
        ),
    ]
